[build]
  command = "pnpm build"
  publish = "dist"

[dev]
  command = "pnpm dev"

[functions]
  directory = ".netlify/functions"

[functions."api/*"]
  included_files = ["src/**"]
[functions."triggerData"]
  # Scheduled function to periodically trigger the data endpoint
  schedule = "*/1 * * * *"  # run every minute
